### ISSUE TITLE
Species not showing

### ISSUE THREAD

**Issue by HW52X** [mcavallo/foundry-vtt-wfrp4e-more-subspecies#18]
After installing this module, the subspecies aren't showing except the Bretonians etc when ticked.

Does this mod require books other than just the standard CR?

**Comment by mcavallo** [comment]
Hi, thank you for reaching out.

The module requires the [WFRP4E System](https://foundryvtt.com/packages/wfrp4e) and the [Core Module](https://cubicle7games.com/warhammer-fantasy-roleplay-foundry-core-module).

Please be aware that only the [enabled datasets](https://github.com/mcavallo/foundry-vtt-wfrp4e-more-subspecies/wiki/Settings#enabled-datasets) will be available for you to use in the character generation. And whenever you change the enabled datasets you need to restart any ongoing character generation (and reload your browser)

**Comment by HW52X** [comment]
Ok,

So I have both of those. When I go into the module settings I see all of the available options: 

![image](https://github.com/mcavallo/foundry-vtt-wfrp4e-more-subspecies/assets/156934160/264a6beb-d582-4633-85e0-8c29a750bc5a)

When I go into character creator I only see the following options: 

![image](https://github.com/mcavallo/foundry-vtt-wfrp4e-more-subspecies/assets/156934160/70ac0b46-b103-41b6-9ce6-47679cb07e44)

I have reloaded everything etc multiple times just to be safe.

**Comment by mcavallo** [comment]
@HW52X thank you for the detailed report. It seems you are missing the subspecies from the `imperial-humans` dataset, I'll take a look as soon as I can and report back.

**Comment by mcavallo** [comment]
@HW52X I found the issue. I'll release the fix very soon. Thanks again for reporting!

**Comment by HW52X** [comment]
Not a problem. Thank you!

**Comment by mcavallo** [comment]
@HW52X I just released a [new version](https://github.com/mcavallo/foundry-vtt-wfrp4e-more-subspecies/releases/tag/v1.1.2) with the fixed dataset. Please let me know if things work on your end after updating!

I'll leave this issue open for a few days.

**Comment by HW52X** [comment]
I have just tested and it works. Thank you.

**Comment by mcavallo** [comment]
Awesome! Thanks again for reporting! 👍
