### ISSUE TITLE
module doesn't work when Foundry uses routePrefix

### ISSUE THREAD

**Issue by grz0** [mcavallo/foundry-vtt-wfrp4e-more-subspecies#22]
It makes a request to `http://serverIP/modules/wfrp4e-more-subspecies/data/somedata.json` but it should to `http://serverIP/routePrefix_here/modules/wfrp4e-more-subspecies/data/somedata.json`
Looks like a bug in `fetchModuleData()` function:
 https://github.com/mcavallo/foundry-vtt-wfrp4e-more-subspecies/blob/4c92056bd1bb0ac4d0afe19d042f0d1a480c89b4/src/lib/utils.js#L84

**Comment by mcavallo** [comment]
Hi @grz0, thank you for reporting. I'll get a patch out a soon as I can!

**Comment by mcavallo** [comment]
@grz0 I just released a [new version](https://github.com/mcavallo/foundry-vtt-wfrp4e-more-subspecies/releases/tag/v2.0.1) that addresses the problem. Please update and let me know if things work on your end!

I'll leave this issue open for a few days.

**Comment by grz0** [comment]
The problem is fixed in the new version. Thank you!

**Comment by mcavallo** [comment]
Awesome! Thank you for the detailed bug report ❤️
