### ISSUE TITLE
"Sleight Of Hand" should be "Sleight of Hand"

### ISSUE THREAD

**Issue by o0mpALoompA** [mcavallo/foundry-vtt-wfrp4e-more-subspecies#26]
Specifically for the Altdorfer subspecies. If you select Sleight Of Hand as a skill and submit your skills, none get submitted and you can't resubmit them. Sleight Of Hand doesn't exist in the compendium.

It works fine of you make a new skill in the compendium called Sleight Of Hand.

You just need to make the "O" in "Of" lowercase for the species.

Honestly surprised the case matters, but the character creator seems like a mess behind the scenes. Why can't you have Ogres and Gnomes on the list at the same time? Why do you have to swap between Rough Nights and Archives II? Why can't species be added to a single list?

**Comment by mcavallo** [comment]
Hi @o0mpALoompA, thank you for the bug report! I will release a patch soon with a fix to this issue, stay tuned.

I share some of the sentiment regarding some of the quirks of the system, it is very brittle as you can see.

**Comment by mcavallo** [comment]
Hi @o0mpALoompA, I just released a new version that fixes the issue.

Any new characters created after installing the [new version](https://github.com/mcavallo/foundry-vtt-wfrp4e-more-subspecies/releases/tag/v2.2.0) should use the right skill. Please update and let me know how things look on your end. For "broken" characters you can probably just rename the skill in the character sheet and it should use the right skill from the compendium.

I'll leave this issue open for a few days in case you have any feedback. Thank you for reporting the issue!

**Comment by o0mpALoompA** [comment]
Works great, that was quick.

**Comment by mcavallo** [comment]
Thanks again for reporting the bug!
